"""
Eval task for Bernoulli classification.

Given a sequence of 0s and 1s generated by one of two biased coins,
the model must classify which coin (A or B) produced the sequence.

Ground-truth Bayesian posteriors are stored in sample metadata for
calibration analysis.

Usage:
    inspect eval inspect_task_bernoulli.py@bernoulli \
        --model hf/local \
        -M model_path=/path/to/checkpoint \
        -T data_path=/path/to/bernoulli.json \
        -T config_path=/path/to/eval_config.yaml
"""

import yaml
from inspect_ai import Task, task
from inspect_ai.dataset import Sample, hf_dataset
from inspect_ai.model import GenerateConfig
from inspect_ai.solver import chain, generate, system_message

from cruijff_kit.tools.inspect.scorers import build_scorers


@task
def bernoulli(
    data_path: str,
    config_path: str = "",
    split: str = "validation",
    temperature: float = 1e-7,
    max_tokens: int = 3,
    use_chat_template: bool = True,
) -> Task:
    """
    Eval task for Bernoulli coin classification.

    Args:
        data_path: Path to JSON file with {"train": [...], "validation": [...]}
        config_path: Path to eval config YAML (reads prompt/system_prompt/scorers)
        split: Which split to evaluate on (default: validation)
        temperature: Generation temperature
        max_tokens: Max tokens to generate
        use_chat_template: If True, use chat format with system message.
    """
    prompt_str = "{input}"
    system_prompt = ""
    config = {}

    if config_path:
        with open(config_path, "r") as f:
            config = yaml.safe_load(f) or {}
        prompt_str = config.get("prompt", "{input}")
        system_prompt = config.get("system_prompt", "")

    def record_to_sample(record):
        formatted_input = prompt_str.format(input=record["input"])
        metadata = record.get("metadata", {})
        return Sample(
            input=formatted_input,
            target=record["output"],
            metadata=metadata,
        )

    dataset = hf_dataset(
        path="json",
        data_files=data_path,
        field=split,
        split="train",
        sample_fields=record_to_sample,
    )

    if use_chat_template:
        solver = chain(
            system_message(system_prompt),
            generate(temperature=temperature, max_tokens=max_tokens),
        )
    else:
        solver = chain(
            generate(temperature=temperature, max_tokens=max_tokens),
        )

    return Task(
        dataset=dataset,
        solver=solver,
        scorer=build_scorers(config),
        config=GenerateConfig(logprobs=True, top_logprobs=20),
    )
