# Default test fixture for scaffold reproducibility testing
#
# A minimal experiment_summary.yaml that exercises both scaffold-torchtune
# and scaffold-inspect subagents. Uses the smallest model and dataset for speed.
#
# 3 runs: 2 fine-tuned (rank4, rank8) + 1 base control
# 1 epoch, 1 eval task — exercises both subagent types with minimal scope
#
# Used by: /test-scaffold-reproducibility (default when no path argument given)

experiment:
  name: "scaffold_repro_test_2026-02-16"
  question: "Test fixture for scaffold reproducibility — not a real experiment."
  date: "2026-02-16"
  purpose: "Verify that scaffolding the same experiment twice produces identical outputs."
  directory: "/scratch/gpfs/MSALGANIK/mjs3/ck-sanity-checks/scaffold_repro_test_2026-02-16"

tools:
  preparation: "torchtune"
  evaluation: "inspect-ai"

variables:
  lora_rank: [4, 8]

controls:
  system_prompt: "You are a helpful assistant."
  prompt: "Capitalize the given word: {input}\n"
  epochs: 1
  batch_size: 4
  validation_during_training: true

models:
  base:
    - name: "Llama-3.2-1B-Instruct"
      path: "/scratch/gpfs/MSALGANIK/pretrained-llms/Llama-3.2-1B-Instruct"
      size_gb: 4.7
      base_recipe: "llama3_2/1B_lora_single_device"

data:
  training:
    - path: "/home/mjs3/cruijff_kit/data/green/capitalization/words_5L_80P_1000.json"
      label: "words_5L_80P_1000"
      format: "json"
      size_kb: 60
      splits:
        train: 800
        validation: 100
        test: 100

output:
  base_directory: "/scratch/gpfs/MSALGANIK/mjs3/ck-outputs/scaffold_repro_test_2026-02-16"
  checkpoint_pattern: "ck-out-{run_name}/epoch_{N}"
  wandb_project: "scaffold-repro-test"

runs:
  - name: "Llama-3.2-1B-Instruct_rank4"
    type: "fine-tuned"
    model: "Llama-3.2-1B-Instruct"
    parameters:
      lora_rank: 4

  - name: "Llama-3.2-1B-Instruct_rank8"
    type: "fine-tuned"
    model: "Llama-3.2-1B-Instruct"
    parameters:
      lora_rank: 8

  - name: "Llama-3.2-1B-Instruct_base"
    type: "control"
    model: "Llama-3.2-1B-Instruct"
    parameters: {}

evaluation:
  system_prompt: "You are a helpful assistant."
  temperature: 0.0
  scorer:
    - name: "match"
      params:
        location: "exact"
        ignore_case: false

  tasks:
    - name: "capitalization"
      script: "/home/mjs3/cruijff_kit/experiments/capitalization/inspect_task_capitalization.py"
      description: "Tests word capitalization accuracy"

  matrix:
    - run: "Llama-3.2-1B-Instruct_rank4"
      tasks: ["capitalization"]
      epochs: [0]

    - run: "Llama-3.2-1B-Instruct_rank8"
      tasks: ["capitalization"]
      epochs: [0]

    - run: "Llama-3.2-1B-Instruct_base"
      tasks: ["capitalization"]
      epochs: null
